language: go

go:
    - "1.10"
    - "1.11"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./coap
  - go build  -o bin/example-server ./example-server
  - go build  -o bin/coap-cli ./coap-cli

after_success:
  - bash <(curl -s https://codecov.io/bash)